<<<<<<< HEAD
version: '3.8'

=======
>>>>>>> upstream/master
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
<<<<<<< HEAD
=======
      - ./tests:/app/tests
>>>>>>> upstream/master
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
<<<<<<< HEAD
    command: mlflow server --host 0.0.0.0
=======
    volumes:
      - ./mlruns:/app/mlruns
    command: mlflow server --host 0.0.0.0 --backend-store-uri sqlite:///app/mlruns/mlflow.db --default-artifact-root /app/mlruns
>>>>>>> upstream/master

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
