global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'heart-disease-api'
    static_configs:
<<<<<<< HEAD
      - targets: ['heart-disease-api-service:80']
=======
      #- targets: ['127.0.0.1:8000']
      - targets: ['api:8000', '127.0.0.1:8000', 'host.docker.internal:8000']
>>>>>>> upstream/master
